import { createHash, randomUUID } from 'node:crypto'
import type { EvidenceItem, EvidenceSnapshot } from '../context/evidence.js'

export const LECTURE_SCHEMA_VERSION = 'lingxi-lecture/v1' as const
export type SlideRole = 'cover' | 'content' | 'section' | 'summary' | 'ending'
export type TeachingPurpose = 'explain' | 'example' | 'counterexample' | 'practice' | 'review' | 'assessment'
export type VisualKind = 'diagram' | 'process' | 'chart' | 'comparison' | 'formula' | 'exercise' | 'source-image'

export interface LectureTheme {
  id: string
  background: string
  surface: string
  text: string
  muted: string
  accent: string
  fontFamily?: string
}

export interface LectureAnchor { id: string; x: number; y: number; width: number; height: number }
export interface LectureStep { id: string; title: string; explanation: string; anchorIds: string[]; claimIds: string[] }
export interface EvidenceBinding {
  claimId: string
  snapshotId: string
  evidenceMarkers: string[]
  kind: 'source' | 'derived' | 'teaching-example'
  statement: string
}
export interface SlideSpec {
  id: string
  order: number
  chapterId: string
  role: SlideRole
  purpose: TeachingPurpose
  title: string
  conclusion: string
  visualKind: VisualKind
  /** Trusted, validated markup generated by the authoring stage; scripts are forbidden. */
  bodyHtml: string
  anchors: LectureAnchor[]
  steps: LectureStep[]
  bindings: EvidenceBinding[]
}
export interface ChapterPlan { id: string; order: number; title: string; objectiveIds: string[]; slideIds: string[] }
export interface CoursePlan {
  title: string
  audience: string
  prerequisites: string[]
  objectives: { id: string; description: string }[]
  chapters: ChapterPlan[]
  targetSlideCount: number
  durationMinutes: number
  terminology: Record<string, string>
}
export interface DeckManifest {
  schemaVersion: typeof LECTURE_SCHEMA_VERSION
  deckId: string
  revision: number
  title: string
  language: string
  theme: LectureTheme
  course: CoursePlan
  slides: SlideSpec[]
  evidence: EvidenceSnapshot[]
  createdAt: string
  contentHash?: string
}
export interface ValidationIssue { code: string; message: string; pageId?: string; objectId?: string }
export interface ValidationReport { passed: boolean; issues: ValidationIssue[] }

const text = (value: unknown, name: string, max = 20_000): string => {
  if (typeof value !== 'string' || !value.trim() || value.length > max) throw new Error(`${name} is invalid`)
  return value
}
const strings = (value: unknown, name: string, max = 500): string[] => {
  if (!Array.isArray(value) || value.length > max || value.some(item => typeof item !== 'string' || !item.trim())) throw new Error(`${name} is invalid`)
  return [...new Set(value)]
}

export function validateCreateRequest(value: unknown): LectureDeckCreateRequest {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('lecture request is invalid')
  const input = value as Record<string, unknown>
  const allowed = new Set(['requirements', 'title', 'sourceIds', 'targetSlideCount', 'language', 'audience', 'durationMinutes', 'theme'])
  if (Object.keys(input).some(key => !allowed.has(key))) throw new Error('unknown lecture request field')
  const targetSlideCount = input['targetSlideCount'] ?? 24
  if (!Number.isSafeInteger(targetSlideCount) || Number(targetSlideCount) < 3 || Number(targetSlideCount) > 100) throw new Error('targetSlideCount must be between 3 and 100')
  const durationMinutes = input['durationMinutes'] ?? Math.max(10, Math.round(Number(targetSlideCount) * 1.5))
  if (!Number.isSafeInteger(durationMinutes) || Number(durationMinutes) < 1 || Number(durationMinutes) > 1_000) throw new Error('durationMinutes is invalid')
  return {
    requirements: text(input['requirements'], 'requirements'),
    targetSlideCount: Number(targetSlideCount), durationMinutes: Number(durationMinutes),
    ...(input['title'] === undefined ? {} : { title: text(input['title'], 'title', 500) }),
    ...(input['language'] === undefined ? {} : { language: text(input['language'], 'language', 50) }),
    ...(input['audience'] === undefined ? {} : { audience: text(input['audience'], 'audience', 2_000) }),
    ...(input['sourceIds'] === undefined ? {} : { sourceIds: strings(input['sourceIds'], 'sourceIds', 200) }),
    ...(input['theme'] === undefined ? {} : { theme: validateTheme(input['theme']) }),
  }
}

export interface LectureDeckCreateRequest {
  requirements: string; title?: string; sourceIds?: string[]; targetSlideCount: number
  language?: string; audience?: string; durationMinutes: number; theme?: LectureTheme
}
export interface LectureDeckRevisionRequest {
  instruction: string; scope: 'page' | 'section' | 'deck'; expectedRevision: number; pageIds?: string[]; sectionIds?: string[]
}

export function validateRevisionRequest(value: unknown): LectureDeckRevisionRequest {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('revision request is invalid')
  const input = value as Record<string, unknown>
  const allowed = new Set(['instruction', 'scope', 'expectedRevision', 'pageIds', 'sectionIds'])
  if (Object.keys(input).some(key => !allowed.has(key))) throw new Error('unknown revision request field')
  if (!['page', 'section', 'deck'].includes(String(input['scope']))) throw new Error('revision scope is invalid')
  if (!Number.isSafeInteger(input['expectedRevision']) || Number(input['expectedRevision']) < 1) throw new Error('expectedRevision is invalid')
  const request = { instruction: text(input['instruction'], 'instruction'), scope: input['scope'] as LectureDeckRevisionRequest['scope'], expectedRevision: Number(input['expectedRevision']),
    ...(input['pageIds'] === undefined ? {} : { pageIds: strings(input['pageIds'], 'pageIds') }),
    ...(input['sectionIds'] === undefined ? {} : { sectionIds: strings(input['sectionIds'], 'sectionIds') }) }
  if (request.scope === 'page' && !request.pageIds?.length) throw new Error('pageIds are required for a page revision')
  if (request.scope === 'section' && !request.sectionIds?.length) throw new Error('sectionIds are required for a section revision')
  return request
}

export const DEFAULT_LECTURE_THEME: LectureTheme = Object.freeze({
  id: 'midnight', background: '#08111f', surface: '#12233d', text: '#f7f9fc', muted: '#a8b6ca', accent: '#53d6c7',
  fontFamily: 'system-ui, -apple-system, "Segoe UI", sans-serif',
})

function validateTheme(value: unknown): LectureTheme {
  if (!value || typeof value !== 'object' || Array.isArray(value)) throw new Error('theme is invalid')
  const theme = value as Record<string, unknown>
  const allowed = new Set(['id', 'background', 'surface', 'text', 'muted', 'accent', 'fontFamily'])
  if (Object.keys(theme).some(key => !allowed.has(key))) throw new Error('unknown theme field')
  const color = (name: string) => {
    const value = theme[name]
    if (typeof value !== 'string' || !/^#[0-9a-f]{6}$/i.test(value)) throw new Error(`theme.${name} is invalid`)
    return value
  }
  return { id: text(theme['id'], 'theme.id', 100), background: color('background'), surface: color('surface'), text: color('text'), muted: color('muted'), accent: color('accent'),
    ...(theme['fontFamily'] === undefined ? {} : { fontFamily: text(theme['fontFamily'], 'theme.fontFamily', 300) }) }
}

export function newPageId(): string { return `pg_${randomUUID().replaceAll('-', '')}` }
export function contentHash(value: unknown): string { return createHash('sha256').update(JSON.stringify(value)).digest('hex') }

export function evidenceFor(snapshot: EvidenceSnapshot, markers: readonly string[]): EvidenceItem[] {
  const wanted = new Set(markers)
  return snapshot.items.filter(item => wanted.has(item.marker))
}
