/** First-release public API: assembled runtime and stable data contracts. */
export { releaseVersions } from './versions.js'
export { createLingxiOS, type LingxiOSOptions, type RequestInput, type LectureRequestInput, type LectureOperationInput, type MessageIdentity, type ActionResolutionInput } from './app/index.js'
export { packageResources } from './app/resources.js'
export { doctor, type DoctorCheck } from './app/doctor.js'
export { ConfigError } from './errors.js'
export { isGoalOutcome, type GoalOutcome, type Verification } from './protocol/outcome.js'
export type { AssistantMessage, RunEvent, KernelArtifact } from './protocol/types.js'
export type { RequestSnapshot } from './context/request.js'
export type { RequestAttachment } from './context/attachments.js'
export type { TaskContract } from './context/task-contract.js'
export type { EvidenceItem, EvidenceSnapshot } from './context/evidence.js'
export type { ResponseEnvelope, CitationAnnotation } from './outcome/envelope.js'
export type { GoalAssessment } from './outcome/assessment.js'
export { DEFAULT_MODEL } from './model/openai.js'
export type { InputContinuation } from './app/input.js'
export type { SqlPool, SqlClient, SqlQueryable } from './control-plane/pg-store.js'
export type { KernelExecutor, ManagedKernelExecutor, KernelHostBridge } from './kernel/manager.js'
